apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-matrix
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/flickers/gitops.git
              revision: HEAD
              files:
                - path: "cluster-apps/**/config.json"
          - pullRequest:
              github:
                # The GitHub organization or user.
                owner: flickers
                # The Github repository
                repo: hallo-world
                # For GitHub Enterprise (optional)
                labels:
                  - preview
              requeueAfterSeconds: 500
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ "{{" }} name {{ "}}" }}-{{ "{{" }} number {{ "}}" }}-{{ "{{" }} cluster {{ "}}" }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ "{{" }} folderPath {{ "}}" }}'
        repo-head-sha: '{{ "{{" }} head_sha {{ "}}" }}'
        wanted-name: '{{ "{{" }} name {{ "}}" }}-{{ "{{" }} branch {{ "}}" }}-{{ "{{" }} number {{ "}}" }}'
    spec:
      project: cluster-apps
      source:
        path: '{{ "{{" }} folderPath {{ "}}" }}'
        targetRevision: HEAD
        repoURL: https://github.com/flickers/gitops.git
        helm:
          parameters:
          - name: 'main.image.tag'
            value: '{{ "{{" }} head_sha {{ "}}" }}'
          valueFiles:
            - '{{ "{{" }} valueFile {{ "}}" }}'
      destination:
        namespace: '{{ "{{" }} namespace {{ "}}" }}'
        name: '{{ "{{" }} cluster {{ "}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true