apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - git:
        repoURL: https://github.com/flickers/gitops.git
        revision: HEAD
        files:
          - path: "cluster-apps/**/config.json"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ "{{" }} name {{ "}}" }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ "{{" }} folderPath {{ "}}" }}'
        argocd-image-updater.argoproj.io/image-list: '{{ "{{" }} name {{ "}}" }}={{ "{{" }} image {{ "}}" }}'
        argocd-image-updater.argoproj.io/{{ "{{" }} name {{ "}}" }}.update-strategy: 'latest'
        argocd-image-updater.argoproj.io/{{ "{{" }} name {{ "}}" }}.allow-tags: 'regexp:^sha-[0-9a-f]{7}$'
    spec:
      project: cluster-apps
      source:
        path: '{{ "{{" }} folderPath {{ "}}" }}'
        targetRevision: HEAD
        repoURL: https://github.com/flickers/gitops.git
        helm:
          valueFiles:
            - '{{ "{{" }} valueFile {{ "}}" }}'
      destination:
        namespace: '{{ "{{" }} namespace {{ "}}" }}'
        name: '{{ "{{" }} cluster {{ "}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true