apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps-feature
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/flickers/gitops.git
              revision: HEAD
              files:
                - path: "cluster-apps/**/config.json"
          - pullRequest:
              github:
                # The GitHub organization or user.
                owner: flickers
                # The Github repository
                repo: hallo-world
                # For GitHub Enterprise (optional)
                # labels:
                #   - preview
              requeueAfterSeconds: 500
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ name }}-pull-{{ number }}-{{ cluster }}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '/{{ folderPath }}'
        repo-head-sha: '{{ head_sha }}'
        wanted-name: '{{ name }}-{{ branch }}-{{ number }}'
    spec:
      project: cluster-apps-feature
      source:
        path: '{{ folderPath }}'
        targetRevision: HEAD
        repoURL: https://github.com/flickers/gitops.git
        helm:
          parameters:
          - name: 'main.image.tag'
            value: '{{ head_sha }}'
          valueFiles:
            - '{{ valueFile }}'
      destination:
        namespace: '{{ namespace }}'
        name: '{{ cluster }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - ApplyOutOfSyncOnly=false
          - CreateNamespace=true
      ignoreDifferences:
      # for the specified json pointers
      - group: "*"
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: "*"
        kind: Deployment
        jsonPointers:
        - /metadata/labels/argocd.argoproj.io/instance