apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    app: hallo-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hallo-world
  template:
    metadata:
      labels:
        app: hallo-world
    spec:
      containers:
      - name: hallo-world
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80