apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    app: {{ include "main.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "main.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "main.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        name: {{ include "main.fullname" . }}
    spec:
      containers:
      - name: main
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        ports:
        - containerPort: 80