apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Cluster Apps
  destinations:
  - name: '*'
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - https://github.com/flickers/gitops.git