cert-manager:
  fullnameOverride: cert-manager
  prometheus:
    servicemonitor:
      enabled: "true"
  installCRDs: true
  volumeMounts:
    - mountPath: /.aws
      name: aws-credentials
      readOnly: true